# Scramble RA and Dec in a FT1 file

In [42]:
from astropy.io import fits
import numpy as np

In [43]:
ft1 = fits.open('/Users/rc/Desktop/rac-AstroServer-00019-ft1.fits',mode='update')
#ft1.info()

Filename: /Users/rc/Desktop/rac-AstroServer-00019-ft1.fits
No.    Name         Type      Cards   Dimensions   Format
0    PRIMARY     PrimaryHDU      32   ()              
1    EVENTS      BinTableHDU    197   3769R x 23C   [E, E, E, E, E, E, E, E, E, D, J, J, I, 3I, 32X, 32X, I, D, E, E, E, E, E]   
2    GTI         BinTableHDU     48   5R x 2C      [D, D]   


In [44]:
#cols = ft1[1].columns
#cols.info()

In [45]:
tbdata = ft1[1].data
tbdata['RA']

array([  7.54764128,   7.54764128,  24.42331886, ...,  28.98826599,
        12.55011845,  28.83041   ], dtype=float32)

In [37]:
tbdata['Dec']

array([ 14.81523514,  25.0424881 ,  13.36471844, ...,  11.87734222,
         8.21503162,  18.88469124], dtype=float32)

In [54]:
ft1[1].data['RA'] = np.roll(ft1[1].data['RA'],1)
ft1[1].data['Dec'] = np.roll(ft1[1].data['Dec'],-1)

In [55]:
ft1.flush()  # changes are written back to original.fits
ft1.close()  # closing the file will also flush any changes and prevent

In [56]:
ft1new = fits.open('/Users/rc/Desktop/rac-AstroServer-00019-ft1.fits')

In [57]:
ft1new[1].data['RA']

array([ 12.55011845,  28.83041   ,   7.54764128, ...,  24.67067337,
        26.67151833,  28.98826599], dtype=float32)

In [58]:
ft1new[1].data['Dec']

array([ 25.0424881 ,  13.36471844,  26.60076141, ...,   8.21503162,
        18.88469124,  14.81523514], dtype=float32)